'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _typedImmutable = require('typed-immutable');

var _HttpCodes = require('./Httpcodes');

var _ErrorCodes = require('./ErrorCodes');

const ErrorCodeMapper = {
  INTERNAL_ERROR: _HttpCodes.HTTP_CODE_500,
  INVALID_REQUEST_QUERY_PARAMETER: _HttpCodes.HTTP_CODE_400,
  INVALID_REQUEST_BODY_PARAMETER: _HttpCodes.HTTP_CODE_400,
  ACCOUNT_NOT_FOUND: _HttpCodes.HTTP_CODE_400,
  EMPLOYEE_SHIFT_NOT_FOUND_ERROR: _HttpCodes.HTTP_CODE_404,
  ALREADY_CLOCKED_OUT: _HttpCodes.HTTP_CODE_400,
  CLOCK_IN_OUT_ENTRIES_NOT_FOUND: _HttpCodes.HTTP_CODE_404,
  CLOCK_IN_OUT_SETTINGS_NOT_FOUND: _HttpCodes.HTTP_CODE_400,
  CLOCKINOUT_ALREADY_DEACTIVE: _HttpCodes.HTTP_CODE_400,
  CLOCKINOUT_ALREADY_ACTIVE: _HttpCodes.HTTP_CODE_400,
  SHIFT_ENTRIES_NOT_FOUND: _HttpCodes.HTTP_CODE_404,
  SHIFT_ALREADY_DEACTIVE: _HttpCodes.HTTP_CODE_400,
  SHIFT_ALREADY_ACTIVE: _HttpCodes.HTTP_CODE_400,
  OVERLAPS_WITH_ACTIVE_SHIFTS: _HttpCodes.HTTP_CODE_400,
  OVERLAPS_WITH_INACTIVE_SHIFTS: _HttpCodes.HTTP_CODE_400,
  OVERLAPS_WITH_ACTIVE_AND_INACTIVE_SHIFTS: _HttpCodes.HTTP_CODE_400,
  CLOCKINOUT_SETTING_ALREADY_EXIST: _HttpCodes.HTTP_CODE_400,
  SIGNATURE_MISMATCH: _HttpCodes.HTTP_CODE_400,
  MESSAGE_HANDLING_FAILED: _HttpCodes.HTTP_CODE_400,
  OVERLAPPING_CLOCKINOUT: _HttpCodes.HTTP_CODE_400,
  SHIFT_REVISION_MISMATCH: _HttpCodes.HTTP_CODE_400,
  REGULARS_CANNOT_REACTIVATE: _HttpCodes.HTTP_CODE_400,
  REGULARS_CANNOT_DEACTIVATE: _HttpCodes.HTTP_CODE_400,
  INVALID_SHIFT_END_TYPE: _HttpCodes.HTTP_CODE_400,
  SHIFT_ALREADY_EXISTS: _HttpCodes.HTTP_CODE_400,
  NO_ACTIVE_CLOCKINOUT_SETTING_FOR_MERCHANT: _HttpCodes.HTTP_CODE_404,
  TIMEZONE_NOT_FOUND: _HttpCodes.HTTP_CODE_400,
  OPEN_SHIFT_DEACTIVATE: _HttpCodes.HTTP_CODE_400,
  CLOCK_IN_OUT_TIME_INVALID: _HttpCodes.HTTP_CODE_400,
  OPEN_CLOCKINOUT_DEACTIVATE: _HttpCodes.HTTP_CODE_400,
  AUTO_CLOCKOUT_ALREADY_IN_PROGRESS: _HttpCodes.HTTP_CODE_403,
  OPEN_SHIFT_EDIT: _HttpCodes.HTTP_CODE_400}

  exports.default = ErrorCodeMapper;